Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,34 +1,114 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
-
-name: Java CI with Gradle
+name: CI Python
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ master ]
   pull_request:
-    branches: [ "master" ]
+    branches: [ master ]
+  release:
+    types: [created]
+      
 
-permissions:
-  contents: read
+env:
+  ## Sets environment variable
+  BUILD_NUMBER: ${{ github.run_number	}}
 
 jobs:
   build:
 
-    runs-on: ubuntu-latest
+    runs-on: [ self-hosted, Windows ]
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
-    - name: Build with Gradle
-      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
-      with:
-        arguments: build
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      - uses: jfrog/setup-jfrog-cli@v3.4.1
+        env:
+          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
+      - run: |
+          //jf rt dl Download binar
+  
+      - name: Build
+        run: |
+          gradle build 
+          
+      - name: Upload 
+        uses: actions/upload-artifact@v3.1.3
+        with: 
+          name: JAR
+          path: STP2API/dist/*.whl
+
+      - name: Pytest
+        run: |
+          gradle test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4.0.3
+        if: always() # always run even if the previous step fails
+        with:
+          require_tests: true
+          fail_on_failure: true
+          report_paths: 'STP2API/test_report.xml'
+  #NEXT Job
+  extra:
+    
+    if: ((github.ref == 'refs/heads/master') || (github.event_name == 'release'))
+    needs: build
+    
+    runs-on: [ self-hosted, Windows ]
+
+    steps:
+           # Runs docs
+      - name: Generate any docs
+        run: |
+          echo doc
+      - name: Checkout wiki code
+        uses: actions/checkout@v2
+        with:
+          repository: ${{github.repository}}.wiki
+          path: wiki
+
+      - name: Make pdf
+        run: |
+          cd wiki
+          python conf.py
+          copy YavaConf_23_manual.pdf ..
+          cd ..
+          7z a Manual.zip YavaConf_23_manual.pdf
+          
+      - name: Upload Manual
+        uses: actions/upload-artifact@v3.1.3
+        with:
+          name: Manual
+          path: YavaConf_23_manual.pdf
+          
+      - name: Upload to BART
+        uses: jfrog/setup-jfrog-cli@v3.4.1
+        env:
+          JF_ENV_1: ${{ secrets.BART_JF_SECRET_ENV_1 }}
+      - run: |
+          //jf rt del Delete old binary
+          //jf rt u upload new binary
+          
+  #NEXT Job
+  release:
+    if: github.event_name == 'release'
+    needs: extra
+    
+    runs-on: [ self-hosted, Windows ]
+    environment: Release Python API
+    steps:
+        
+      - name: Upload to BART Ofical
+        uses: jfrog/setup-jfrog-cli@v3.4.1
+        env:
+          JF_ENV_1: ${{ secrets.BART_JF_SECRET_ENV_1 }}
+      - run: |
+          echo "---------------------------------------" > ChangeLog.txt
+          echo "    YavaConf 2023 ChangeLog" >> ChangeLog.txt
+          echo "---------------------------------------" >> ChangeLog.txt
+          echo "    Tag Name: ${{ github.event.release.tag_name }}" >> ChangeLog.txt
+          echo "    Release Name: ${{ github.event.release.name }}" >> ChangeLog.txt
+          echo "---------------------------------------" >> ChangeLog.txt
+          echo "${{ github.event.release.body }}" >> ChangeLog.txt
+          //jf rt u copy build to offical
+
